<a href="https://colab.research.google.com/github/AdityaPatil1705/Python/blob/main/Numpy.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

**What is NumPy?**

1. NumPy is a Python library used for working with arrays.

2. It also has functions for working in domain of linear algebra, fourier transform, and matrices.

3. NumPy stands for Numerical Python.

**Why Use NumPy?**

1. In Python we have lists that serve the purpose of arrays, but they are slow to process.

2. NumPy aims to provide an array object that is up to 50x faster than traditional Python lists.

3. The array object in NumPy is called ndarray, it provides a lot of supporting functions that make working with ndarray very easy.

4. Arrays are very frequently used in data science, where speed and resources are very important.

In [1]:
import numpy as np

In [2]:
print(np.__version__)

1.26.4


**Array Creation**

In [3]:
#0D Array
arr = np.array(45)
print(arr)
print("Dimensions: ",arr.ndim)
print(type(arr))

45
Dimensions:  0
<class 'numpy.ndarray'>


In [4]:
#1D Array
arr = np.array([23,45,67,77])
print("Dimensions: ",arr.ndim)
print(arr)

Dimensions:  1
[23 45 67 77]


In [5]:
#2D Array
arr = np.array([[23,45,67,77],[56,88,25,78]])
print("Dimensions: ",arr.ndim)
print(arr)

Dimensions:  2
[[23 45 67 77]
 [56 88 25 78]]


In [6]:
#3D Array
arr = np.array([[[23,45,67,77],[56,88,25,78]],[[65,84,92,45],[97,54,21,44]]])
print("Dimensions: ",arr.ndim)
print(arr)

Dimensions:  3
[[[23 45 67 77]
  [56 88 25 78]]

 [[65 84 92 45]
  [97 54 21 44]]]


When the array is created, you can define the number of dimensions by using the ndmin argument.

In [7]:
arr = np.array([54,87,98,77,54],ndmin=5)
print("Dimensions: ",arr.ndim)
print(arr)

Dimensions:  5
[[[[[54 87 98 77 54]]]]]


**Accessing Elements**

In [8]:
arr = np.array([23,45,67,77])
print(arr[2])

67


In [9]:
arr = np.array([[[23,45,67,77],[56,88,25,78]],[[65,84,92,45],[97,54,21,44]]])
print(arr)
print("Accessing 1st element from 3rd array from 2nd Array: ",arr[1,0,0])

[[[23 45 67 77]
  [56 88 25 78]]

 [[65 84 92 45]
  [97 54 21 44]]]
Accessing 1st element from 3rd array from 2nd Array:  65


In [10]:
arr = np.array([[1,2,3,4,5], [6,7,8,9,10]])
print('Last element from 2nd dim: ', arr[1, -1])

Last element from 2nd dim:  10


**Slicing**

In [11]:
arr = np.array([1, 2, 3, 4, 5, 6, 7])
print(arr[1:5])

[2 3 4 5]


In [12]:
arr = np.array([1, 2, 3, 4, 5, 6, 7])    #Step
print(arr[1:5:2])

[2 4]


In [13]:
#From the second element, slice elements from index 1 to index 4
arr = np.array([[1, 2, 3, 4, 5], [6, 7, 8, 9, 10]])
print(arr[1, 1:4])

[7 8 9]


In [14]:
#From both elements, return index 2:
arr = np.array([[1, 2, 3, 4, 5], [6, 7, 8, 9, 10]])
print(arr[0:2, 2])

[3 8]


In [15]:
arr = np.array([[1, 2, 3, 4, 5], [6, 7, 8, 9, 10]])
print(arr[0:2, 1:4])

[[2 3 4]
 [7 8 9]]


**Datatype**

1. i = integer
2. b = boolean
3. f = float
4. S = String
5. U = Unicode String

In [16]:
arr = np.array([1, 2, 3, 4])
print(arr.dtype)

int64


We use the array() function to create arrays, this function can take an optional argument: dtype that allows us to define the expected data type of the array elements:

In [17]:
arr = np.array([1, 2, 3, 4], dtype='S')
print(arr)
print(arr.dtype)

[b'1' b'2' b'3' b'4']
|S1


Converting Data Type on Existing Arrays

1. The best way to change the data type of an existing array, is to make a copy of the array with the astype() method.

2. The astype() function creates a copy of the array, and allows you to specify the data type as a parameter.

3. The data type can be specified using a string, like 'f' for float, 'i' for integer etc. or you can use the data type directly like float for float and int for integer.

In [18]:
arr = np.array([0,1,1,0,5,0,0,8,7])
print(arr.dtype)

arrCopy = arr.astype(bool)
print(arrCopy)
print(arrCopy.dtype)

int64
[False  True  True False  True False False  True  True]
bool


In [19]:
arr = np.array([1.1, 2.1, 3.7])
newarr = arr.astype("i")
print(newarr)
print(newarr.dtype)

[1 2 3]
int32


The Difference Between Copy and View

1. The main difference between a copy and a view of an array is that the copy is a new array, and the view is just a view of the original array.

2. The copy owns the data and any changes made to the copy will not affect original array, and any changes made to the original array will not affect the copy.

3. The view does not own the data and any changes made to the view will affect the original array, and any changes made to the original array will affect the view.

In [20]:
arr = np.array([1,2,3,4,5,6])
print(arr)

copied = arr.copy()
copied[0] = 40
print(copied)

[1 2 3 4 5 6]
[40  2  3  4  5  6]


In [21]:
arr = np.array([1,2,3,4,5])
x = arr.view()

arr[0] = 50
print(arr)
print(x)

[50  2  3  4  5]
[50  2  3  4  5]


Every NumPy array has the attribute base that returns None if the array owns the data.

In [22]:
arr = np.array([1,2,3,4,5])

x = arr.view()
y = arr.copy()

print(x.base)
print(y.base)

[1 2 3 4 5]
None


**Shape of an Array**

The shape of an array is the number of elements in each dimension.

In [23]:
arr = np.array([[1,2,3,4],[5,6,7,8]])
print(arr.ndim)
print(arr.shape)

2
(2, 4)


In [24]:
arr = np.array([1,2,3],ndmin=5)
print(arr)
print(arr.shape)

[[[[[1 2 3]]]]]
(1, 1, 1, 1, 3)


**Reshaping arrays**

1. Reshaping means changing the shape of an array.

2. The shape of an array is the number of elements in each dimension.

3. By reshaping we can add or remove dimensions or change number of elements in each dimension.

In [25]:
arr = np.array([1,2,3,4,5,6,7,8,9,10])
x = arr.reshape(2,5)

print(arr)
print("Dimension: ",arr.ndim)
print(x)
print("Dimension: ",x.ndim)

[ 1  2  3  4  5  6  7  8  9 10]
Dimension:  1
[[ 1  2  3  4  5]
 [ 6  7  8  9 10]]
Dimension:  2


In [26]:
arr = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12])
newarr = arr.reshape(2, 3, 2)
print(newarr)

[[[ 1  2]
  [ 3  4]
  [ 5  6]]

 [[ 7  8]
  [ 9 10]
  [11 12]]]


In [27]:
arr = np.array([1, 2, 3, 4, 5, 6, 7, 8])
print(arr.reshape(2, 4).base)

[1 2 3 4 5 6 7 8]


Unknown Dimension

You are allowed to have one "unknown" dimension.

Meaning that you do not have to specify an exact number for one of the dimensions in the reshape method.

Pass -1 as the value, and NumPy will calculate this number for you.

In [28]:
arr = np.array([1, 2, 3, 4, 5, 6, 7, 8])
newarr = arr.reshape(2, 2, -1)
print(newarr)

[[[1 2]
  [3 4]]

 [[5 6]
  [7 8]]]


In [29]:
arr = np.array([[1, 2, 3], [4, 5, 6]])
newarr = arr.reshape(-1)
print(newarr)

[1 2 3 4 5 6]


**Iterating Arrays**

In [30]:
arr = np.array([1,2,3,4,5,6,7,8])
for x in arr:
  print(x)

1
2
3
4
5
6
7
8


In [31]:
arr = np.array([[1,2,3],[4,5,6]])
for x in arr:
  print(x)

#2nd way
print("Another Way For Scaler")
for x in arr:
  for y in x:
    print(y)

[1 2 3]
[4 5 6]
Another Way For Scaler
1
2
3
4
5
6


In [32]:
arr = np.array([[[1,2,3],[4,5,6]],[[7,8,9],[10,11,12]]])
for x in arr:
  print(x)

#2nd way
print("Another Way For Scaler")
for x in arr:
  for y in x:
    for z in y:
      print(z)

[[1 2 3]
 [4 5 6]]
[[ 7  8  9]
 [10 11 12]]
Another Way For Scaler
1
2
3
4
5
6
7
8
9
10
11
12


**nditer Method:**

In [33]:
arr = np.array([[[1,2,3],[4,5,6]],[[7,8,9],[10,11,12]]])
for x in np.nditer(arr):
  print(x)


1
2
3
4
5
6
7
8
9
10
11
12


**Enumerated Iteration Using ndenumerate()**

Enumeration means mentioning sequence number of somethings one by one.

Sometimes we require corresponding index of the element while iterating, the ndenumerate() method can be used for those usecases.

In [34]:
arr = np.array([1, 2, 3])

for idx, x in np.ndenumerate(arr):
  print(idx, x)

(0,) 1
(1,) 2
(2,) 3


In [35]:
arr = np.array([[1, 2, 3, 4], [5, 6, 7, 8]])

for idx, x in np.ndenumerate(arr):
  print(idx, x)

(0, 0) 1
(0, 1) 2
(0, 2) 3
(0, 3) 4
(1, 0) 5
(1, 1) 6
(1, 2) 7
(1, 3) 8


**Iterating Array With Different Data Types**

We can use op_dtypes argument and pass it the expected datatype to change the datatype of elements while iterating.

NumPy does not change the data type of the element in-place (where the element is in array) so it needs some other space to perform this action, that extra space is called buffer, and in order to enable it in nditer() we pass flags=['buffered'].

In [36]:
arr = np.array([1, 2, 3])

for x in np.nditer(arr, flags=["buffered"], op_dtypes='S'):
  print(x)

b'1'
b'2'
b'3'


**Joining Array**

Joining means putting contents of two or more arrays in a single array.

In SQL we join tables based on a key, whereas in NumPy we join arrays by axes.

We pass a sequence of arrays that we want to join to the concatenate() function, along with the axis. If axis is not explicitly passed, it is taken as 0.

In [37]:
arr1 = np.array([1,2,3,4])
arr2 = np.array([5,6,7,8])

arr = np.concatenate((arr1,arr2))
print(arr)

[1 2 3 4 5 6 7 8]


In [38]:
arr1 = np.array([[1, 2], [3, 4]])
arr2 = np.array([[5, 6], [7, 8]])

arr = np.concatenate((arr1, arr2),axis = 1)
print(arr)

[[1 2 5 6]
 [3 4 7 8]]


Joining Arrays Using Stack Functions

Stacking is same as concatenation, the only difference is that stacking is done along a new axis.

We can concatenate two 1-D arrays along the second axis which would result in putting them one over the other, ie. stacking.

We pass a sequence of arrays that we want to join to the stack() method along with the axis. If axis is not explicitly passed it is taken as 0.

In [39]:
arr1 = np.array([1, 2, 3])
arr2 = np.array([4, 5, 6])

arr = np.stack((arr1, arr2), axis=1)
print(arr)

[[1 4]
 [2 5]
 [3 6]]


In [40]:
#NumPy provides a helper function: hstack() to stack along rows.

arr1 = np.array([1, 2, 3])
arr2 = np.array([4, 5, 6])

arr = np.hstack((arr1, arr2))
print(arr)

[1 2 3 4 5 6]


In [41]:
#NumPy provides a helper function: vstack()  to stack along columns.

arr1 = np.array([1,2,3,4])
arr2 = np.array([5,6,7,8])

arr = np.vstack((arr1,arr2))
print(arr)

[[1 2 3 4]
 [5 6 7 8]]


In [42]:
#NumPy provides a helper function: dstack() to stack along height, which is the same as depth.

arr1 = np.array([1,2,3,4])
arr2 = np.array([5,6,7,8])

arr = np.dstack((arr1,arr2))
print(arr)

[[[1 5]
  [2 6]
  [3 7]
  [4 8]]]


**Splitting NumPy Arrays**

Splitting is reverse operation of Joining.

Joining merges multiple arrays into one and Splitting breaks one array into multiple.

We use array_split() for splitting arrays, we pass it the array we want to split and the number of splits.

In [43]:
arr = np.array([1,2,3,4,5,6])

x = np.array_split(arr,3)
print(x)

[array([1, 2]), array([3, 4]), array([5, 6])]


In [44]:
print(x[0])
print(x[1])
print(x[2])

[1 2]
[3 4]
[5 6]


**Search**

In [45]:
arr = np.array([1, 2, 3, 4, 5, 6, 7, 8])
x = np.where(arr%2 == 0)
print(x)

(array([1, 3, 5, 7]),)


In [46]:
arr = np.array([1, 2, 3, 4, 5, 6, 5, 8])

x = np.searchsorted(arr, 5)
print(x)

4


**Sort**

In [47]:
arr = np.array([[3, 2, 4], [5, 0, 1]])
print(np.sort(arr))

[[2 3 4]
 [0 1 5]]


**Filter Array**

Filter array for printing even numbers

In [48]:
arr = np.array([1,2,3,4,5,6,7,8,9])

filter_Arr = []

for i in arr:
  if i%2 == 0:
    filter_Arr.append(True)
  else:
    filter_Arr.append(False)
print(filter_Arr)

newArr = arr[filter_Arr]

print(newArr)

[False, True, False, True, False, True, False, True, False]
[2 4 6 8]


In [49]:
arr = np.array([1,2,3,4,5,6,7,8,9])
filter_Arr = arr%2 == 0

newArr = arr[filter_Arr]
print(newArr)

[2 4 6 8]
